name: Deploy WorldSense-GDELT to AWS

on:
  push:
    branches: [ dev ]


jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID1 }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY1 }}
          aws_region: us-east-1
          function_name: myfunction2
          source: example/index.js
  deploy-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Zip Lambda function
        run: |
          cd example/api
          zip function.zip lambda_function.py # Add your main Lambda handler files

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY1 }}
          aws-region: us-east-1

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \
            --zip-file fileb:///example/api/function.zip